name: "Test the build"

on:
  push:
  pull_request:

jobs:
  test:
    name: test if ssm-parent can be built
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: go.mod

      - name: download dependencies
        run: go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9

      - name: build the app
        run: go build
      - name: test the app
        run: go test -v ./...
